### ISSUE TITLE
Cannot compile on macOS arm64 Sequoia 15.5 (24F74)

### ISSUE THREAD

**Issue by neilt** [EnterpriseDB/system_stats#47]
When following the instructions in the readme on GitHub I get the following error.

```bash
<redacted> system_stats-3.2 % PATH="/opt/local/lib/postgresql17/bin:$PATH" make USE_PGXS=1
...
...
...
/usr/bin/clang -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Werror=unguarded-availability-new -Wendif-labels -Wmissing-format-attribute -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-unused-command-line-argument -Wno-compound-token-split-by-macro -Wno-cast-function-type-strict -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX15.sdk   -fvisibility=hidden -I. -I./ -I/opt/local/include/postgresql17/server -I/opt/local/include/postgresql17/internal  -I/opt/local/include -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX15.sdk -I/opt/local/include/libxml2  -I/opt/local/include  -c -o system_stats.o system_stats.c
clang: warning: no such sysroot directory: '/Library/Developer/CommandLineTools/SDKs/MacOSX15.sdk' [-Wmissing-sysroot]
system_stats.c:10:10: fatal error: 'stdio.h' file not found
   10 | #include <stdio.h>
      |          ^~~~~~~~~
1 error generated.
make: *** [system_stats.o] Error 1

<redacted> system_stats-3.2 % xcode-select -p
/Applications/Xcode.app/Contents/Developer

<redacted> system_stats-3.2 % system_profiler SPDeveloperToolsDataType
Developer:

    Developer Tools:

      Version: 16.4 (16F6)
      Location: /Applications/Xcode.app
      Applications:
          Xcode: 16.4 (23792)
          Instruments: 16.4 (64570.99.5)
      SDKs:
          DriverKit:
              24.5: 
          iOS:
              18.5: (22F76)
          iOS Simulator:
              18.5: (22F76)
          macOS:
              15.5: (24F74)
          tvOS:
              18.5: (22L572)
          tvOS Simulator:
              18.5: (22L572)
          visionOS:
              2.5: (22O473)
          visionOS Simulator:
              2.5: (22O473)
          watchOS:
              11.5: (22T572)
          watchOS Simulator:
              11.5: (22T572)

<redacted> system_stats-3.2 % uname -a
Darwin <redacted>.localdomain 24.5.0 Darwin Kernel Version 24.5.0: Tue Apr 22 19:54:43 PDT 2025; root:xnu-11417.121.6~2/RELEASE_ARM64_T8132 arm64
```
